---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
        name: "TOML Syntax Checking"
      - id: check-yaml
        name: "YAML Syntax Checking"
      - id: check-json
        name: "JSON Syntax Checking"
      - id: pretty-format-json
        name: "JSON Code Formatting"
        args:
          - "--autofix"
          - "--indent"
          - "4"
          - "--no-ensure-ascii"
      - id: end-of-file-fixer
        name: "Final Newline Checking"
      - id: trailing-whitespace
        name: "Trailing Whitespace Checking"

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "Python Import Sorting"
        args:
          - "--profile"
          - "black"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        name: "Python Syntax Unification"
        args:
          - "--py37-plus"

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: "Black Code Formatting"
        args:
          - "--line-length"
          - "79"

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: "Flake8 Style Checking"
        # additional_dependencies:
        #   - "flake8-docstrings==1.6.0"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
        name: "YAML Style Checking"

  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        name: "Xenon Code Complexity Checking"
        args:
          - "--max-absolute=B"
          - "--max-modules=A"
          - "--max-average=A"
